server:
  port: 19881
spring:
  application:
    name: guide-user
eureka:
  client:
    service-url:
     defaultZone: http://localhost:19880/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh