server:
  port: 19880
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 注册中心自身不注册flase，在注册中心集群开启true
     register-with-eureka: false
     # 注册中心，自身不做服务检索
     fetch-registry: false