server:
  port: 20002
spring:
  application:
    name: z-guide-config-sever
  cloud:
   config:
    server:
     git:
       uri: https://github.com/yanghaichuan/z-guide-config.git
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:19880/eureka/