server:
  port: 20001
spring:
  application:
    name: guide-consumer
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:19880/eureka/
  instance:
    instance-id: ${srping.application.name}:${server.port}
    prefer-ip-address: true
feign:
  httpclient:
    connection-timeout: 3000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000