server:
  port: 19891
  servlet:
    context-path: /sso
spring:
  application:
    name: guide-auth-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 60ms
        max-idle: 8
        min-idle: 0
    timeout: 10000
eureka:
  client:
    service-url:
     defaultZone: http://localhost:19880/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh